### ISSUE TITLE
bash: syntax error near unexpected token `URL' when running `cv2.VideoCapture('URL')`

### ISSUE THREAD

**Issue by vedranius** [akmamun/live-stream-face-detection#3]
When I try to run:
`cv2.VideoCapture("URL")`

I get an error: 
`bash: syntax error near unexpected token "URL"`

What might be the problem?
Tnx!

**Comment by akmamun** [comment]
If you want to see in webcam use cv2.VideoCapture(0).
otherwise, replace "URL" with valid rtsp_camera_url .
